---

- name: copy dotfiles
  copy: src={{ item }}
        dest=/home/{{ username }}/.{{ item }}
        owner={{ username }}
        group={{ username }}
        mode=0644
  with_items:
    - profile
    - bashrc
  tags:
    - deploy

- name: change perms
  file: path=/home/{{ username }}/.rvm
        owner={{ username }}
        group=rvm
        recurse=yes
  tags:
    - deploy
