---

- name: copy dotfiles
  copy: src={{ item }}
        dest=/home/{{ username }}/.{{ item }}
        owner={{ username }}
        group={{ username }}
        mode=0644
  with_items:
    - profile
  tags:
    - deploy
